import {
  IconBabyCarriage,
  IconBarbell,
  IconBeach,
  IconBeer,
  IconBolt,
  IconBook,
  IconBriefcase,
  IconBuildingBank,
  IconBus,
  IconCar,
  IconCoffee,
  IconDeviceGamepad2,
  IconDeviceMobile,
  IconDots,
  IconFirstAidKit,
  IconGasStation,
  IconGift,
  IconGlassFull,
  IconHome,
  IconMovie,
  IconMusic,
  IconPaw,
  IconPigMoney,
  IconPill,
  IconPizza,
  IconPlane,
  IconPlant2,
  IconReceiptRefund,
  IconRepeat,
  IconSchool,
  IconScissors,
  IconShirt,
  IconShoppingBag,
  IconShoppingCart,
  IconSparkles,
  IconTicket,
  IconTool,
  IconToolsKitchen2,
  IconWallet,
  IconWifi,
  type Icon,
} from '@tabler/icons-react'

/** Icone disponibili per le categorie, per nome. */
export const CATEGORY_ICONS: Record<string, Icon> = {
  cart: IconShoppingCart,
  home: IconHome,
  bolt: IconBolt,
  bus: IconBus,
  kitchen: IconToolsKitchen2,
  coffee: IconCoffee,
  glass: IconGlassFull,
  health: IconFirstAidKit,
  shirt: IconShirt,
  repeat: IconRepeat,
  gift: IconGift,
  dots: IconDots,
  briefcase: IconBriefcase,
  sparkles: IconSparkles,
  refund: IconReceiptRefund,
  wallet: IconWallet,
  car: IconCar,
  fuel: IconGasStation,
  plane: IconPlane,
  beach: IconBeach,
  book: IconBook,
  school: IconSchool,
  gym: IconBarbell,
  pet: IconPaw,
  baby: IconBabyCarriage,
  phone: IconDeviceMobile,
  wifi: IconWifi,
  pill: IconPill,
  movie: IconMovie,
  music: IconMusic,
  game: IconDeviceGamepad2,
  pizza: IconPizza,
  beer: IconBeer,
  bag: IconShoppingBag,
  scissors: IconScissors,
  tool: IconTool,
  plant: IconPlant2,
  ticket: IconTicket,
  bank: IconBuildingBank,
  piggy: IconPigMoney,
}

export function CategoryIcon({ name, size = 22 }: { name?: string; size?: number }) {
  const Cmp = (name && CATEGORY_ICONS[name]) || IconDots
  return <Cmp size={size} stroke={1.8} aria-hidden="true" />
}
